# SELECT T1.BRANCH_ID, T1.NAME
#     FROM EMPLOYEES T1
#         LEFT JOIN (SELECT BRANCH_ID, MAX(SALARY) as SALARY FROM EMPLOYEES
#     GROUP BY BRANCH_ID ORDER BY BRANCH_ID) T2
#         ON T1.BRANCH_ID = T2.BRANCH_ID
#             WHERE T1.BRANCH_ID = T2.BRANCH_ID AND T1.SALARY = T2.SALARY
#             ORDER BY BRANCH_ID , NAME
#
#
#
#
#
# -- SELECT BRANCH_ID, MAX(SALARY) as SALARY FROM EMPLOYEES
# --     GROUP BY BRANCH_ID
# --         ORDER BY BRANCH_ID
#
# -- SELECT SALARY, BRANCH_ID FROM EMPLOYEES order by branch_id
#
# -- SELECT * FROM EMPLOYEES T1 ORDER BY T1.SALARY DESC
# -- SELECT * FROM EMPLOYEES GROUP BY BRANCH_ID ORDER BY BRANCH_ID
#
#
# -- SELECT BRANCH_ID, MAX(SALARY) FROM EMPLOYEES
# --     GROUP BY BRANCH_ID ORDER BY BRANCH_ID